# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = """
zsh-defer -c "$(cat <<'SHELDON_DEFER'
{{ hooks?.pre | nl }}{% for file in files %}source "{{ file }}"
{% endfor %}{{ hooks?.post | nl }}SHELDON_DEFER
)"
"""

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

[plugins.dotfiles-core]
local = "~/.dotfiles/config/sheldon/modules"
use = [
  "environment/init.zsh",
  "helper/init.zsh",
  "editor/init.zsh",
  "history/init.zsh",
  "directory/init.zsh",
  "spectrum/init.zsh",
  "utility/init.zsh",
]
apply = ["source"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]
hooks.post = "zsh-defer source ~/.dotfiles/config/sheldon/modules/zsh-autosuggestions/init.zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]
hooks.post = "zsh-defer source ~/.dotfiles/config/sheldon/modules/zsh-history-substring-search/init.zsh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]
